// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')

async function postJob(){
  try {
    driver = await new Builder().forBrowser('firefox').build()
    await driver.manage().window().maximize()
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.id("exampleInputEmail2")).click()
    await driver.findElement(By.id("exampleInputEmail2")).sendKeys("flipkart@gmail.com")
    await driver.findElement(By.id("exampleInputPassword2")).click()
    await driver.findElement(By.id("exampleInputPassword2")).sendKeys("flipkart")
    await driver.findElement(By.css(".card:nth-child(2) .ui")).click()
    await driver.findElement(By.linkText("Jobs")).click()
    await driver.findElement(By.css(".green")).click()
    await driver.findElement(By.id("exampleInputTitle1")).click()
    await driver.findElement(By.id("exampleInputTitle1")).sendKeys("Frontend Developer")
    await driver.findElement(By.id("exampleInputDescription1")).click()
    await driver.findElement(By.id("exampleInputDescription1")).sendKeys("Assist in making the web UI more creative")
    await driver.findElement(By.id("exampleInputSkills1")).click()
    await driver.findElement(By.id("exampleInputSkills1")).sendKeys("Angular, Bootstrap")
    await driver.findElement(By.id("exampleInputDate1")).click()
    await driver.findElement(By.id("exampleInputDate1")).sendKeys("2020-11-20")
    
    setTimeout(async () => {
        await driver.findElement(By.css(".btn")).click()
    }, 2000);

    setTimeout(async () => {
      await driver.quit();
    }, 7000);
    
  } catch (error) {
    console.log("error--",error);
  }
    
}

postJob();
