// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')

async function registerUser(){
  try {
    driver = await new Builder().forBrowser('firefox').build()
    await driver.manage().window().maximize()
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Recruiter Registration")).click()
    await driver.findElement(By.id("exampleInputCompany1")).click()
    await driver.findElement(By.id("exampleInputCompany1")).sendKeys("Facebook")
    await driver.findElement(By.id("exampleInputEmail1")).click()
    await driver.findElement(By.id("exampleInputEmail1")).sendKeys("facebook@gmail.com")
    await driver.findElement(By.id("exampleInputContact1")).click()
    await driver.findElement(By.id("exampleInputContact1")).sendKeys("7388078953")
    await driver.findElement(By.id("exampleInputPassword1")).click()
    await driver.findElement(By.id("exampleInputPassword1")).sendKeys("facebook")
    setTimeout(async () => {
      await driver.findElement(By.css(".btn")).click()
    }, 2000);

    setTimeout(async () => {
      await driver.quit();
    }, 7000);
    
  } catch (error) {
    console.log("error--",error);
  }
    
}

registerUser();
