// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')

async function registerUser(){
  try {
    driver = await new Builder().forBrowser('firefox').build()
    await driver.manage().window().maximize()
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.id("exampleInputEmail2")).click()
    await driver.findElement(By.id("exampleInputEmail2")).sendKeys("flipkart@gmail.com")
    await driver.findElement(By.id("exampleInputPassword2")).click()
    await driver.findElement(By.id("exampleInputPassword2")).sendKeys("flipkart")
    await driver.findElement(By.css(".card:nth-child(2) .ui")).click()
    
    setTimeout(async () => {
        await driver.findElement(By.linkText("Jobs")).click()
    }, 2000);
    
    setTimeout(async () => {
        await driver.findElement(By.css(".col-lg-4:nth-child(3) > .ui .ui")).click()
    }, 4000);
    
    setTimeout(async () => {
        await driver.findElement(By.css(".ui")).click()
    }, 6000);

    setTimeout(async () => {
      await driver.quit();
    }, 11000);
    
  } catch (error) {
    console.log("error--",error);
  }
    
}

registerUser();
