// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('RegisterUser', function() {
  this.timeout(3000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    //await driver.quit();
  })
  it('RegisterUser', async function() {
    done();
    await driver.get("http://localhost:3000/")
    await driver.manage().window().maximize()
    await driver.findElement(By.linkText("User Registration")).click()
    await driver.findElement(By.id("exampleInputName1")).click()
    await driver.findElement(By.id("exampleInputName1")).sendKeys("Shubham Raj")
    await driver.findElement(By.id("exampleInputDob1")).click()
    await driver.findElement(By.id("exampleInputDob1")).sendKeys("1999-03-29")
    await driver.findElement(By.id("exampleInputEmail1")).click()
    await driver.findElement(By.id("exampleInputEmail1")).sendKeys("shubham@gmail.com")
    await driver.findElement(By.id("exampleInputPassword1")).click()
    await driver.findElement(By.id("exampleInputPassword1")).sendKeys("shubham")
    await driver.findElement(By.css(".btn")).click()
  }).catch(done)
})
